### ISSUE TITLE
Regroup parts of the public API to reduce how many modules we must import before solving an ODE

### ISSUE THREAD

**Issue by pnkraemer** [pnkraemer/probdiffeq#747]
**Context:** 
To solve an ODE with probdiffeq, a user needs to import many modules even though there exist multiple pairs of modules that are always used together and even depend on each other in some cases.
For example, here is the header of the `Probabilistic solvers as collocation methods` tutorial:

```python
"""Demonstrate how probabilistic solvers work via conditioning on constraints."""

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from diffeqzoo import backend

from probdiffeq import adaptive, ivpsolve, timestep
from probdiffeq.impl import impl
from probdiffeq.solvers import markov, uncalibrated
from probdiffeq.solvers.strategies import fixedpoint
from probdiffeq.solvers.strategies.components import corrections, priors
from probdiffeq.taylor import autodiff
from probdiffeq.util.doc_util import notebook
```

**What:**
I suggest merging the following modules:
- [x] `adaptive` and `controls` because they are always used together (done in #745)
- [x] `timestep` and `ivpsolve` because they are always used together (done in #746)
- [x]  `solvers.uncalibrated`, `solvers.calibrated` (e.g. in `probdiffeq.solvers.py`) because every time we choose a different solver, we currently have to change the imports (which is tedious!)  (done in #750)
- [x] `solvers.markov` and `solvers.solution` (e.g.  in `probdiffeq.stats` or similar) because it is currently unclear where one starts and the other one stops (done in #755)
- [x] all strategies in `probdiffeq.solvers.strategies` because they share most code (done in #751) 
- [x] all solver-components content of `solvers.components` to a single module because we need one of each to build the solver (and put them together in a strategy). Importing a different module for every function we use is tedious. Most of these modules contain a single function. (done in #753)
- [x] Combine strategies and components since we still need one of each (done in #756)
- [x] Combine ivpsolve.py and adaptive.py since we always use them together (done in #757)
- [x] Combine components with solvers to clarify how to build a solver (done in #758) 
- [x] Combine all modules in taylor.py into a single module to make the code more accessible (done in #760)

These changes break the existing API. Therefore, the next version (after completing this issue) will increase the minor version, not the patch version. 

**More context:**
* There exists a bunch of code duplication. I anticipate that this will be easier to remove once duplicating functions are in the same module.

**Comment by pnkraemer** [comment]
This issue is now resolved. For an update, here is how the above-linked header changed:

```python
"""Demonstrate how probabilistic solvers work via conditioning on constraints."""

import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt
from diffeqzoo import backend

from probdiffeq import ivpsolve, ivpsolvers, stats, taylor
from probdiffeq.impl import impl
from probdiffeq.util.doc_util import notebook
```
